const BASE = "http://localhost:5000/api/v1.0/";
const ID_KEY = "identity";

/**
 * @brief enroll user in system
 * @param lts_id LTS unique id
 * @param success function returns the secret generated by backend
 * @param error function returns any error result
 */
function enroll(lts_id, success, error) {
    const payload = {
        'lts_id' : lts_id,
        'secret' : ''
    };
    $.ajax({
        type: 'POST',
        url: BASE + 'enroll?' + $.param(payload),
        success: function (data) {
            console.debug("Secret: " + JSON.stringify(data));
            success(data);
        },
        error: function (data) {
            error(data);
        }
    });
}

/**
 * @brief Fetch the stats of specified user
 * @param student_id LTS unique id for user
 * @param secret authorization token to prevent impersonation
 * @param callback callback receives fetched data
 * @param err callback receives raw ajax error
 */
function fetchStats(student_id, secret, callback, err) {
    scrapeCoursePageInfo(function(courseInfo) {
        const payload = {
            'lts_id': student_id,
            'secret': secret,
            'course_id': courseInfo['courseid']
        };
        $.ajax({
            type: 'GET',
            url: BASE + 'stats?' + $.param(payload),
            success: function (data) {
                callback(data);
            },
            error: function (data) {
                err(data);
            },
            complete: function () {
                $('#spinner').hide();
            }
        });
    });
}

/**
 * @brief Send course info to server, we don't care what happens
 * @param student_id for auth
 * @param secret for auth
 */
function addCourse(student_id, secret) {
    scrapeCoursePageInfo(function(courseInfo) {
        const payload = {
            'lts_id' : student_id,
            'secret' : secret,
            'course_id' : courseInfo['courseid'],
            'course_name' : courseInfo['coursename']
        };
        $.ajax({
            type: 'POST',
            url: BASE + 'addcourse?' + $.param(payload)
        });
    });
}

/**
 * @brief Build an HTML data containing stats data
 * @param classes dictionary containing stats
 * @returns {*|jQuery|HTMLElement}
 */
function makeOverviewTable(classes) {

    var keys = [];
    for (var key in classes) {
        if (classes.hasOwnProperty(key)) keys.push(key);
    }

    var $table = $('<table/>');
    $table.append('<tr>' +
    '<th> Course </th>' +
    '<th> Today </th>' +
    '<th> This Week </th>' +
    '<th> All Time </th>' +
    '</tr>');
    $table.addClass('bordered');

    for(var i=0; i<keys.length; i++){

        var key = keys[i];
        var data = classes[key];

        if(data.archived) {
            key = key +  '<span class="badge new" data-badge-caption="Archived"></span>'
        }

        $table.append( '<tr>' +
            '<td>' + key + '</td>' +
            '<td>' + data.day + '</td>' +
            '<td>' + data.week + '</td>' +
            '<td>' + data.total + '</td>' +
            '</tr>');
    }
    return $table;
}

/**
 * @brief Build an HTML data containing tone data
 * @param classes dictionary containing stats
 * @returns {*|jQuery|HTMLElement}
 */
function makeGenericTable(classes) {

    var keys = [];
    for (var key in classes) {
        if (classes.hasOwnProperty(key)) keys.push(key);
    }

    var $table = $('<table/>');
    $table.append('<tr>' +
    '<th> Attribute </th>' +
    '<th> Score </th>' +
    '</tr>');
    $table.addClass('bordered');

    for(var i=0; i<keys.length; i++){

        var key = keys[i];
        var data = classes[key];

        $table.append( '<tr>' +
            '<td>' + key + '</td>' +
            '<td>' + data + '</td>' +
            '</tr>');
    }
    return $table;
}

/**
 * @brief Create a greeting based on current time
 * @returns {{phrase: string, title: string}}
 */
function makeGreeting() {
    var now = new Date();
    var tod = "";

    // After 3am and before noon is morning
    if(now.getHours() > 3 && now.getHours() < 12) {
        tod = "morning";
    } else if(now.getHours() < 17) {
        // before 5pm is afternoon
        tod = "afternoon";
    } else {
        tod = "evening";
    }

    return {
        phrase: "Good " + tod,
        title: document.title
    };
}

/**
 * @brief Handles fetching remote data and building out UI
 * @param identity Piazza identity string in format user|secret
 * @param err callback function receives raw AJAX error
 */
function setGreeting(identity, err) {

    const student_id = identity[ID_KEY].split('|')[0];
    const secret = identity[ID_KEY].split('|')[1];

    addCourse(student_id, secret);

    fetchStats(student_id, secret, function (courseData) {

        var username = (typeof courseData.nickname === 'undefined') ? '' : ', ' + courseData.nickname;
        var info = makeGreeting();

        $(".greeting").text(info.phrase + username);

        var main_content = $('#main-content');
        main_content.show();
        main_content.empty().append('<span class="gray-text text-darken-2">Your Piazza</span>');

        if(Object.keys(courseData).length > 0) {

            $('#engagement').append(makeOverviewTable(courseData['stats']));
            $('#quality').append(makeGenericTable(courseData['quality']));
            $('#tone').append(makeGenericTable(courseData['tone']));

        } else if (retry > 0) {
            console.info("Class data is not yet ready");
            main_content.empty().append('<span class="gray-text text-darken-2">Class data is not yet ready</span>');
        }
    }, err);
}

/**
 * @brief Identify the course by looking at the URL and tab name
 * @details this will fail if you are debugging so the else clause
 *  returns mock data. Fitting :)
 * @param callback to pass scraped info to
 */
function scrapeCoursePageInfo(callback) {
     chrome.tabs.query({'active': true, 'lastFocusedWindow': true}, function (tabs) {
         var activeTab = tabs[0];
         if (activeTab) {
             var title = activeTab.title;
             var url = activeTab.url;

             var courseName = title.split('(')[0];
             var courseId = url.split('/')[4];
             if(courseId.indexOf('?') >= 0) {
                 courseId = courseId.split('?')[0];
             }
             console.debug("Course Info: " + courseName, courseId);
             callback({'coursename' : courseName, 'courseid' : courseId });
         } else {
             console.info("Failed to get course data from current tab, using mock data");
             callback({'coursename' : 'OMS CS6460', 'courseid' : 'j6azklk4gaf4v9' });
         }
     });
}

/**
 * @brief Get user id from Piazza token then go ask our backend
 * for a secret
 */
function identifyUser(success, error) {
    chrome.cookies.get({"url": "https://piazza.com", "name": "last_piaz_user"}, function (student_id) {
        enroll(student_id.value, function (data) {
            var identity = {};
            identity[ID_KEY] = student_id.value + '|' + data['keep_this'];

            chrome.storage.sync.set(identity, function() {
                if(chrome.runtime.error) {
                    console.info("Failed to store identity");
                    error(chrome.runtime.error);
                } else {
                    success(identity, error);
                }
            });
        }, error);
    });
}


/**
 * On DOM load, begin the authorization process
 */
function initApp() {

    $('#spinner').show();

    function initErr(error) {
        $(".greeting").text("Ooops, something went wrong");
        console.log(JSON.stringify(error));
    }

    chrome.storage.sync.get(ID_KEY, function(identity) {
        if (!chrome.runtime.error) {
            if(Object.keys(identity).length === 0) {
                console.debug("Creating new user");
                identifyUser(setGreeting, initErr);
            } else {
                console.debug("Using current identity");
                setGreeting(identity, initErr);
            }
        } else {
            $(".greeting").text("Ooops, I couldn't retrieve your token");
            console.error(chrome.runtime.error);
        }
    });
}

window.onload = function() {
    // TODO on uninstall we need to purge from our database somehow... hmm.
    //chrome.runtime.setUninstallURL(BASE);
    initApp()
};